---
title: "Callaway Santanna Group-time ATT"
author: "DSE Group 3"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Importing relevant packages**
```{r, echo=TRUE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(did)
```

**Importing all cleaned data**
```{r}
df <- readRDS("../cleaned_data/finalmerged.rds")
```

**Remove all observations where year > repeal date**
```{r}
df1 <- df %>%
  filter(is.na(repeal_year) | YEAR <= repeal_year)
```

```{r}
colnames(df1)
```


```{r}
df1$treat_start_year[is.na(df1$treat_start_year)] <- 0
```


```{r}
att_cs <- att_gt(
  yname   = "birth_lastyear",
  tname   = "YEAR",
  gname   = "treat_start_year",
  xformla = ~ AGE + NCHILD + EDUC + RACE + MARST,
  control_group = "nevertreated",
  weightsname = "ASECWT",
  data    = df1,
  panel = F,
  clustervars = "STATEFIP"
)
```
```{r}
summary(att_cs)
```

```{r}
agg_cs <- aggte(att_cs, type = "group")
summary(agg_cs)
```
```{r}
agg_dyn <- aggte(att_cs, type = "dynamic")
summary(agg_dyn)
ggdid(agg_dyn)
```
```{r}
library(fixest)   

# 2) EVENT-STUDY (Sun–Abraham), binary outcome → LPM
#    Keep INDIVIDUAL covariates; cluster at state; add state & year FE
m_birth <- feols(
  birth_lastyear ~ sunab(treat_start_year, YEAR) + AGE + EDUC + RACE + MARST |
    STATEFIP + YEAR,
  data = df1,
  weights = ~ASECWT,           # drop this line if you don't want weights
  cluster = ~STATEFIP
)

summary(m_birth)
etable(m_birth, se = "cluster")
post <- coef(m_birth)[grepl("event::", names(coef(m_birth))) & !grepl("event_\\-", names(coef(m_birth)))]
mean(post)   # simple average of post coefficients
```


```{r}
iplot(m_birth, ref.line = 0, xlab = "Event time (years)", main = "Births < 1 (SA event-study)")
```



